version: '3'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: ryu-blog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
      MYSQL_DATABASE: ryu_blog
      TZ: Asia/Shanghai
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - ryu-blog-network

  # Redis缓存
  redis:
    image: redis:7.0-alpine
    container_name: ryu-blog-redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - ryu-blog-network

  # 应用服务
  app:
    build: .
    container_name: ryu-blog-app
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      - DB_URL=r2dbc:mysql://mysql:3306/ryu_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD:-123456}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - SERVER_PORT=8080
      - UPLOAD_PATH=/data/uploads
      - JWT_SECRET=${JWT_SECRET:-abcdefghijklmnopqrstuvwxyz1234567890}
    volumes:
      - app-uploads:/data/uploads
    ports:
      - "8080:8080"
    networks:
      - ryu-blog-network

networks:
  ryu-blog-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  app-uploads: 