spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: warn
    com.ryu.blog: info
    org.springframework.r2dbc: warn
    io.r2dbc.pool: warn
  file:
    name: /var/log/ryu-blog/app.log
    max-size: 10MB
    max-history: 30

# 生产环境下禁用Swagger
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Sa-Token配置
sa-token:
  # JWT密钥
  jwt-secret-key: ${JWT_SECRET}
  # token有效期，单位s 默认1天
  timeout: 86400

# 应用配置
app:
  # 文件上传配置
  upload:
    base-path: ${UPLOAD_PATH:/data/uploads}
  # 缓存配置
  cache:
    article:
      expire: 12h
    category:
      expire: 24h
    tag:
      expire: 24h
    comment:
      expire: 1h

# 日志配置
logging:
  level:
    root: warn
    com.ryu.blog: info
    org.springframework.r2dbc: warn
    io.r2dbc.spi.Statement: warn

# 应用自定义配置
app:
  # 跨域配置
  cors:
    allowed-origins: https://www.example.com 