server:
  port: 5300
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024
  undertow:
    threads:
      io: 16
      worker: 256
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: ryu-blog
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  lifecycle:
    timeout-per-shutdown-phase: 30s
  webflux:
    base-path: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:475118582}
      database: 0
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://localhost:3306/ryu_blog_webflux?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:475118582}
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
      max-idle-time: 30m
  codec:
    max-in-memory-size: 10MB

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-128
  token-prefix: Bearer
  # 是否输出操作日志
  is-log: false
  # 是否尝试从 header 里读取 Token
  is-read-header: true
  # 是否尝试从 cookie 里读取 Token
  is-read-cookie: false
  # jwt秘钥
  jwt-secret-key: ${JWT_SECRET:abcdefghijklmnopqrstuvwx}
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 475118582
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

# 日志配置
logging:
  level:
    root: info
    com.ryu.blog: debug
    org.springframework.r2dbc: info
    io.r2dbc.pool: info
    cn.dev33.satoken: debug
  file:
    name: logs/ryu-blog.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 应用自定义配置
app:
  # 文件上传配置
  upload:
    base-path: ${UPLOAD_PATH:./uploads}
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,webp,mp4,mp3,pdf,doc,docx,xls,xlsx,ppt,pptx,zip,rar,7z
  # 跨域配置
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
    exposed-headers: "Content-Disposition,Content-Length,Content-Type,Authorization"
  # 缓存配置
  cache:
    article:
      expire: 1h
    category:
      expire: 1h
    tag:
      expire: 1h
    comment:
      expire: 10m
  # 安全配置
  security:
    # 不需要认证的路径
    ignore-paths: /auth/login,/auth/register,/auth/captcha,/auth/captcha/**,/auth/check,/content/article/list,/content/article/detail/**,/content/category/list,/content/tag/list,/ip/info,/ip/query

# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: true
    urls-primary-name: Ryu Blog API
  group-configs:
    - group: 认证
      paths-to-match: /auth/**
    - group: 内容
      paths-to-match: /content/**
    - group: 用户
      paths-to-match: /user/**
    - group: 系统
      paths-to-match: /sys/**
    - group: IP
      paths-to-match: /ip/**
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  model-and-view-allowed: false
  show-actuator: true 