spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ryu_blog_webflux?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 475118582
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 475118582

# 日志配置
logging:
  level:
    root: debug
    com.ryu: debug
    org.springframework.r2dbc: debug
    io.r2dbc.mysql: debug 