spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ryu_blog_webflux?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 475118582
  data:
    redis:
      host: localhost
      port: 6379
      password: 475118582
      database: 0

# Sa-Token配置
sa-token:
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 475118582

# 日志配置
logging:
  level:
    root: info
    com.ryu.blog: debug
    org.springframework.r2dbc: debug
    io.r2dbc.pool: debug

# 应用自定义配置
app:
  # 文件上传配置
  upload:
    # 上传路径
    path: D:/data/upload

# 开发环境下启用Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true 